spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/C:/Users/user1/Desktop/assignment/reactbackend/tdb
      driver-class-name: org.h2.Driver
      username: sa
      password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true


server:
  port: 8888

servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true